Prepare blog for production
jetthoughts/jetthoughts.github.io pull request #15
Opened 2024-06-04 10:33 UTC by dgorodnichy

2024-06-05 12:44 UTC, pftg commented
@dgorodnichy please add csv file with redirects for cloudflare, and add there all support redirects: latest, trending, root

2024-06-05 12:44 UTC, pftg requested changes
Left some stuff

2024-06-05 12:53 UTC, dgorodnichy commented
@pftg , File with redirects is already in master. You can find it here: https://github.com/jetthoughts/jetthoughts.github.io/blob/master/seo/redirects.csv

2024-06-06 07:22 UTC, pftg approved these changes

2024-06-06 07:22 UTC, merged